### ISSUE TITLE
Python installation failed

### ISSUE THREAD

**Issue by dingjr27** [xmake-io/xmake-repo#2065]
### Xmake Version

2.7.8

### Operating System Version and Architecture

Opensuse 15.4

### Describe Bug

`xmake q -f -v`

```
Looking in links: /tmp/tmp1khkzamy
Processing /tmp/tmp1khkzamy/setuptools-65.5.0-py3-none-any.whl
Processing /tmp/tmp1khkzamy/pip-22.3.1-py3-none-any.whl
Installing collected packages: setuptools, pip
  WARNING: The scripts pip3 and pip3.11 are installed in '/home/aaaa/.xmake/packages/p/python/3.11.3/b2dd6aae0f1d47588fc1174ca0e05614/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-22.3.1 setuptools-65.5.0
/home/aaaa/.xmake/packages/p/python/3.11.3/b2dd6aae0f1d47588fc1174ca0e05614/bin/python -m pip install --upgrade --force-reinstall pip
Could not find platform dependent libraries <exec_prefix>
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/aaaa/.xmake/packages/p/python/3.11.3/b2dd6aae0f1d47588fc1174ca0e05614/lib/python3.11/site-packages/pip/__main__.py", line 29, in <module>
    from pip._internal.cli.main import main as _main
  File "/home/aaaa/.xmake/packages/p/python/3.11.3/b2dd6aae0f1d47588fc1174ca0e05614/lib/python3.11/site-packages/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/home/aaaa/.xmake/packages/p/python/3.11.3/b2dd6aae0f1d47588fc1174ca0e05614/lib/python3.11/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/home/aaaa/.xmake/packages/p/python/3.11.3/b2dd6aae0f1d47588fc1174ca0e05614/lib/python3.11/site-packages/pip/_internal/cli/main_parser.py", line 5, in <module>
    import subprocess
  File "/home/aaaa/.xmake/packages/p/python/3.11.3/b2dd6aae0f1d47588fc1174ca0e05614/lib/python3.11/subprocess.py", line 104, in <module>
    from _posixsubprocess import fork_exec as _fork_exec
ModuleNotFoundError: No module named '_posixsubprocess'
error: execv(/home/aaaa/.xmake/packages/p/python/3.11.3/b2dd6aae0f1d47588fc1174ca0e05614/bin/python -m pip install --upgrade --force-reinstall pip) failed(1)
  => install python 3.11.3 .. failed
error: install failed!
```

### Expected Behavior

Should be able to install python3.10

**Comment by xq114** [comment]
https://discuss.python.org/t/solved-self-compiled-python-is-missing-basic-features-like-readline-and-posixsubprocess/23465/6 It seems some python modules are not correctly built. Could you provide the full build log by
```
xmake q -f -vD > python.log
```
or 
```
xrepo install -vD python > python.log
```
?

**Comment by dingjr27** [comment]
[python.log](https://github.com/xmake-io/xmake-repo/files/11420959/python.log)

**Comment by xq114** [comment]
`xrepo update-repo` and try it again
