### ISSUE TITLE
xmake 安装 glad 失败

### ISSUE THREAD

**Issue by LILKOTYO** [xmake-io/xmake-repo#4051]
### Xmake 版本

2.8.9

### 操作系统版本和架构

Windows 10 22H2

### 描述问题

在 `xmake.lua` 文件中 `add_requires("spdlog", "glfw", "glad")` 并构建项目后 glad 安装失败。
后尝试使用 `xrepo install glad` 同样失败。

### 期待的结果

=> install glad 0.1.36 .. ✔

### 工程配置

xmake.lua 内容如下：
```
set_project("ProjectName")
set_version("1.0.0")

add_rules("mode.debug", "mode.release", "plugin.vsxmake.autoupdate")
add_requires("spdlog", "glfw", "glad")

if is_plat("windows") then
    add_defines("FM_PLATFORM_WINDOWS")
end

if is_mode("debug") then
	add_defines("FM_ENABLE_ASSERTS")
end

target("MyTarget")
    set_kind("shared")
    set_languages("c17", "cxx20")
    set_pcxxheader("MyTarget/fmpch.h")
    add_files("MyTarget/**.cpp")
    add_includedirs("MyTarget")
    add_headerfiles("MyTarget/**.h")
    add_defines("FM_BUILD_DLL")
    add_packages("spdlog", "glfw", "glad")
target_end()

target("Sandbox")
    set_kind("binary")
    set_languages("c17","cxx20")
    set_pcxxheader("MyTarget/fmpch.h")
    add_files("Sandbox/src/**.cpp")
    add_includedirs("MyTarget")
    add_deps("MyTarget")
    add_packages("spdlog")
    add_headerfiles("Sandbox/src/**.h")
target_end()


```

### 附加信息和错误日志

```
生成启动时间为 5/17/2024 11:09:41 AM。

     1>项目“C:\Users\UserName\AppData\Local\.xmake\cache\packages\2405\g\glad\v0.1.36\source\build_d134e486\GLAD.sln”在节点 1 上(Rebuild 个目标)。
     1>ValidateSolutionConfiguration:
         正在生成解决方案配置“Release|x64”。
       ValidateProjects:
         在解决方案配置“Release|x64”中未选定生成项目“INSTALL”。
     1>项目“C:\Users\UserName\AppData\Local\.xmake\cache\packages\2405\g\glad\v0.1.36\source\build_d134e486\GLAD.sln”(1)正在节点 2 上生成“C:\Users\UserName\AppData\Local\.xmake\cache\packages\2405\g\glad\v0.1.36\source\build_d134e486\ZERO_CHECK.vcxproj”(5) (Rebuild 个目标)。
     5>CoreClean:
         正在创建目录“x64\Release\ZERO_CHECK\”。
       PrepareForBuild:
         已启用结构化输出。编译器诊断的格式设置将反映错误层次结构。有关详细信息，请参阅 https://aka.ms/cpp/structured-output。
         正在创建目录“x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\”。
       InitializeBuildStatus:
         正在创建“x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
         正在对“x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild”执行 Touch 任务。
       CustomBuild:
         1>Checking Build System
       FinalizeBuildStatus:
         正在删除文件“x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild”。
         正在对“x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\ZERO_CHECK.lastbuildstate”执行 Touch 任务。
     5>已完成生成项目“C:\Users\UserName\AppData\Local\.xmake\cache\packages\2405\g\glad\v0.1.36\source\build_d134e486\ZERO_CHECK.vcxproj”(Rebuild 个目标)的操作。
     1>项目“C:\Users\UserName\AppData\Local\.xmake\cache\packages\2405\g\glad\v0.1.36\source\build_d134e486\GLAD.sln”(1)正在节点 1 上生成“C:\Users\UserName\AppData\Local\.xmake\cache\packages\2405\g\glad\v0.1.36\source\build_d134e486\ALL_BUILD.vcxproj.metaproj”(2) (Rebuild 个目标)。
     2>项目“C:\Users\UserName\AppData\Local\.xmake\cache\packages\2405\g\glad\v0.1.36\source\build_d134e486\ALL_BUILD.vcxproj.metaproj”(2)正在节点 1 上生成“C:\Users\UserName\AppData\Local\.xmake\cache\packages\2405\g\glad\v0.1.36\source\build_d134e486\glad.vcxproj.metaproj”(3) (Rebuild 个目标)。
     3>项目“C:\Users\UserName\AppData\Local\.xmake\cache\packages\2405\g\glad\v0.1.36\source\build_d134e486\glad.vcxproj.metaproj”(3)正在节点 1 上生成“C:\Users\UserName\AppData\Local\.xmake\cache\packages\2405\g\glad\v0.1.36\source\build_d134e486\glad-generate-files.vcxproj.metaproj”(4) (Rebuild 个目标)。
     4>项目“C:\Users\UserName\AppData\Local\.xmake\cache\packages\2405\g\glad\v0.1.36\source\build_d134e486\glad-generate-files.vcxproj.metaproj”(4)正在节点 1 上生成“C:\Users\UserName\AppData\Local\.xmake\cache\packages\2405\g\glad\v0.1.36\source\build_d134e486\glad-generate-files.vcxproj”(6) (Rebuild 个目标)。
     6>CoreClean:
         正在创建目录“x64\Release\glad-generate-files\”。
       PrepareForBuild:
         已启用结构化输出。编译器诊断的格式设置将反映错误层次结构。有关详细信息，请参阅 https://aka.ms/cpp/structured-output。
         正在创建目录“x64\Release\glad-generate-files\glad-gen.DBBAC395.tlog\”。
       InitializeBuildStatus:
         正在创建“x64\Release\glad-generate-files\glad-gen.DBBAC395.tlog\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
         正在对“x64\Release\glad-generate-files\glad-gen.DBBAC395.tlog\unsuccessfulbuild”执行 Touch 任务。
       ComputeCustomBuildOutput:
         正在创建目录“C:\Users\UserName\AppData\Local\.xmake\cache\packages\2405\g\glad\v0.1.36\source\build_d134e486\include\glad\”。
         正在创建目录“C:\Users\UserName\AppData\Local\.xmake\cache\packages\2405\g\glad\v0.1.36\source\build_d134e486\src\”。
       CustomBuild:
         “‘C:\Users\UserName\AppData\Local\.xmake\cache\packages\2405\g\glad\v0.1.36\source\build_d134e486\CMakeFiles\d248094b5be0952cc9e851af82e48954\glad-generate-files.rule’的生成依赖于由‘C:\Users\UserName\AppData\Local\.xmake\cache\packages\2405\g\glad\v0.1.36\source\build_d134e486\CMakeFiles\f2c1dc2f62825ddf14951b7d5852c0d3\glad.h.rule’的生成所产生的‘C:\USERS\UserName\APPDATA\LOCAL\.XMAKE\CACHE\PACKAGES\2405\G\GLAD\V0.1.36\SOURCE\BUILD_D134E486\INCLUDE\GLAD\GLAD.H’。无法并行生成项。”
         Generating GLAD
         [05/17/2024 11:09:42][INFO	][glad   	]: reproducible build, using packaged specification: 'gl.xml'
         [05/17/2024 11:09:42][INFO	][glad.files	]: opening 'gl.xml' from packaged path
         Traceback (most recent call last):
           File "<frozen runpy>", line 198, in _run_module_as_main
           File "<frozen runpy>", line 88, in _run_code
           File "C:\Users\UserName\AppData\Local\.xmake\cache\packages\2405\g\glad\v0.1.36\source\glad\__main__.py", line 192, in <module>
             main()
           File "C:\Users\UserName\AppData\Local\.xmake\cache\packages\2405\g\glad\v0.1.36\source\glad\__main__.py", line 151, in main
             spec = get_spec(spec_name, reproducible=ns.reproducible)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           File "C:\Users\UserName\AppData\Local\.xmake\cache\packages\2405\g\glad\v0.1.36\source\glad\__main__.py", line 43, in get_spec
             return spec_cls.from_file(glad.files.open_local(value + '.xml'))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           File "C:\Users\UserName\AppData\Local\.xmake\cache\packages\2405\g\glad\v0.1.36\source\glad\parse.py", line 74, in from_file
             return cls(xml_frompath(path))
                        ^^^^^^^^^^^^^^^^^^
           File "C:\Users\UserName\AppData\Local\.xmake\cache\packages\2405\g\glad\v0.1.36\source\glad\parse.py", line 20, in xml_frompath
             return etree.parse(path).getroot()
                    ^^^^^^^^^^^^^^^^^
           File "C:\Users\UserName\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 1203, in parse
             tree.parse(source, parser)
           File "C:\Users\UserName\AppData\Local\Programs\Python\Python312\Lib\xml\etree\ElementTree.py", line 568, in parse
             self._root = parser._parse_whole(source)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
         UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 2: illegal multibyte sequence
     6>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(254,5): error MSB8066: “C:\Users\UserName\AppData\Local\.xmake\cache\packages\2405\g\glad\v0.1.36\source\build_d134e486\CMakeFiles\f2c1dc2f62825ddf14951b7d5852c0d3\glad.h.rule;C:\Users\UserName\AppData\Local\.xmake\cache\packages\2405\g\glad\v0.1.36\source\build_d134e486\CMakeFiles\d248094b5be0952cc9e851af82e48954\glad-generate-files.rule;C:\Users\UserName\AppData\Local\.xmake\cache\packages\2405\g\glad\v0.1.36\source\CMakeLists.txt”的自定义生成已退出，代码为 1。 [C:\Users\UserName\AppData\Local\.xmake\cache\packages\2405\g\glad\v0.1.36\source\build_d134e486\glad-generate-files.vcxproj]
     6>已完成生成项目“C:\Users\UserName\AppData\Local\.xmake\cache\packages\2405\g\glad\v0.1.36\source\build_d134e486\glad-generate-files.vcxproj”(Rebuild 个目标)的操作 - 失败。
     4>已完成生成项目“C:\Users\UserName\AppData\Local\.xmake\cache\packages\2405\g\glad\v0.1.36\source\build_d134e486\glad-generate-files.vcxproj.metaproj”(Rebuild 个目标)的操作 - 失败。
     3>已完成生成项目“C:\Users\UserName\AppData\Local\.xmake\cache\packages\2405\g\glad\v0.1.36\source\build_d134e486\glad.vcxproj.metaproj”(Rebuild 个目标)的操作 - 失败。
     2>已完成生成项目“C:\Users\UserName\AppData\Local\.xmake\cache\packages\2405\g\glad\v0.1.36\source\build_d134e486\ALL_BUILD.vcxproj.metaproj”(Rebuild 个目标)的操作 - 失败。
     1>已完成生成项目“C:\Users\UserName\AppData\Local\.xmake\cache\packages\2405\g\glad\v0.1.36\source\build_d134e486\GLAD.sln”(Rebuild 个目标)的操作 - 失败。

生成失败。

       “C:\Users\UserName\AppData\Local\.xmake\cache\packages\2405\g\glad\v0.1.36\source\build_d134e486\GLAD.sln”(Rebuild 目标) (1) ->
       “C:\Users\UserName\AppData\Local\.xmake\cache\packages\2405\g\glad\v0.1.36\source\build_d134e486\ALL_BUILD.vcxproj.metaproj”(Rebuild 目标) (2) ->
       “C:\Users\UserName\AppData\Local\.xmake\cache\packages\2405\g\glad\v0.1.36\source\build_d134e486\glad.vcxproj.metaproj”(Rebuild 目标) (3) ->
       “C:\Users\UserName\AppData\Local\.xmake\cache\packages\2405\g\glad\v0.1.36\source\build_d134e486\glad-generate-files.vcxproj.metaproj”(Rebuild 目标) (4) ->
       “C:\Users\UserName\AppData\Local\.xmake\cache\packages\2405\g\glad\v0.1.36\source\build_d134e486\glad-generate-files.vcxproj”(Rebuild 目标) (6) ->
       (CustomBuild 目标) -> 
         C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(254,5): error MSB8066: “C:\Users\UserName\AppData\Local\.xmake\cache\packages\2405\g\glad\v0.1.36\source\build_d134e486\CMakeFiles\f2c1dc2f62825ddf14951b7d5852c0d3\glad.h.rule;C:\Users\UserName\AppData\Local\.xmake\cache\packages\2405\g\glad\v0.1.36\source\build_d134e486\CMakeFiles\d248094b5be0952cc9e851af82e48954\glad-generate-files.rule;C:\Users\UserName\AppData\Local\.xmake\cache\packages\2405\g\glad\v0.1.36\source\CMakeLists.txt”的自定义生成已退出，代码为 1。 [C:\Users\UserName\AppData\Local\.xmake\cache\packages\2405\g\glad\v0.1.36\source\build_d134e486\glad-generate-files.vcxproj]

    0 个警告
    1 个错误

已用时间 00:00:01.56


```

**Comment by star-hengxing** [comment]
Windows python 默认使用系统编码打开文件，但 cmake/msbuild 应该会处理好这个。
检查一下本地环境变量有哪些，比如 `PYTHONUTF8`
ref: https://docs.python.org/zh-cn/3/library/os.html#python-utf-8-mode

**Comment by star-hengxing** [comment]
我看了下源码：https://github.com/Dav1dde/glad/blob/1ecd45775d96f35170458e6b148eb0708967e402/glad/files/__init__.py

`resource_exists` 因为某种原因返回 false 了，所以 fallback 到用 python 的 open 打开文件（默认为系统编码）

```python
    if resource_exists(__name__, name):
        logger.info('opening \'%s\' from packaged resource', name)
        return resource_stream(__name__, name)
```

你把包描述拷贝下来，然后把第 29 行换成下面代码试试。

```lua
local envs = import("package.tools.cmake").buildenvs(package, configs)
envs = os.joinenvs(envs, {PYTHONUTF8 = "1"})
import("package.tools.cmake").install(package, configs, {envs = envs})
```

**Comment by star-hengxing** [comment]
这里应该算上游 glad 的 bug，可以去给他们提 issue

**Comment by LILKOTYO** [comment]
> 我看了下源码：https://github.com/Dav1dde/glad/blob/1ecd45775d96f35170458e6b148eb0708967e402/glad/files/__init__.py
> 
> `resource_exists` 因为某种原因返回 false 了，所以 fallback 到用 python 的 open 打开文件（默认为系统编码）
> 
> ```python
>     if resource_exists(__name__, name):
>         logger.info('opening \'%s\' from packaged resource', name)
>         return resource_stream(__name__, name)
> ```
> 
> 你把包描述拷贝下来，然后把第 29 行换成下面代码试试。
> 
> ```lua
> local oldenvs = os.addenvs({PYTHONUTF8 = "1"})
> import("package.tools.cmake").install(package, configs)
> os.setenvs(oldenvs)
> ```
> 
> 如果不改包描述，可以自己手动设置这个环境变量试试。

谢谢xingxing！
